### ISSUE TITLE
Frontend milestone

### ISSUE THREAD

**Issue by kryr34** [jykuo-love-shiritori/twp#150]
- Unresolved tasks in #94
  - [x] ViewShop #141
  - [x] Order #143
  - [x] Product #135
  - [x] Coupon #108
  - [x] Cart #135
  - [x] Admin Manage User #114
  - [x] Search #134 #136
- [x] navbar (依照身分改) #144
- [x] seller/admin icon,name (按鈕上面那個) #145
- [x] crop image (套用objectFit就好) #145
