### ISSUE TITLE
Implement OAuth2.0 PKCE flow

### ISSUE THREAD

**Issue by NOOBDY** [jykuo-love-shiritori/twp#46]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implement OAuth2.0 PKCE flow based on the following RFCs

- https://datatracker.ietf.org/doc/html/rfc6749
- https://datatracker.ietf.org/doc/html/rfc7636

**Describe alternatives you've considered**
Session cookie, but not interesting enough and I have too much time

**Additional context**
N/A

**Todo List**
- [x] `/signup` endpoint for adding new user
- [x] `/oauth/authorize` endpoint for verifying the user
- [x] `/oauth/token` endpoint for getting JWT
- [x] `/oauth/refresh` endpoint for refreshing JWT
- [x] `IsRole()` middleware for verifying JWT
- [x] add `/login` frontend path for initiating PKCE flow
- [x] add `/authorize` frontend path for login input
- [x] add `/callback` frontend path for token exchange
